### ISSUE TITLE
Nftables

### ISSUE THREAD

**Issue by mdomore** [nleiva/capirca_acl#2]
Hi,
I am in the process of moving from iptables to nftables.
I try to re-use as mutch as possible of my actual configuration.

After testing my policy files with capirca I am confiant that they are generating the need policies.

I have created a new task like this
```
  - name: Nftables - Generate ACL for INPUT
    nleiva.capirca_acl.translate:
      platform: 'nftables'
      filter_options:
          - inet
      def_folder: "{{ def_folder }}"
      pol_file: "{{ input }}"
      comment: "INPUT policy for nftables."
    register: input_res
```

First I have some doubt about filter_options values in nftables and the documentation is not clear for me.
How can I specify :
- inet
- input
- 0 (for weight)

Second I have try with a polici file like that : 
```
header {
  target:: nftables
}

# Default policies

# This NFTables ACL generator generates stateful policies via conntrack

term base-allow-icmp-in {
  protocol:: icmp
  icmp-type:: echo-request
  action:: accept
}
```
I have an error : 
```
raise NoTermsError('no terms found')\ncapirca.lib.policy.NoTermsError: no terms found\n"
```

And with a policy file like that : 
```
# Default policies

# This NFTables ACL generator generates stateful policies via conntrack

term base-allow-icmp-in {
  protocol:: icmp
  icmp-type:: echo-request
  action:: accept
}
```
I have an error : 
```
capirca.lib.nftables.HeaderError: Invalid header for Nftables. Required fields missing.
```

I have tried several different options but can find the right one. Do you have an example for nftables ?
Thanks.

I have check in capirca documentation and i see :
```
target:: nftables [chain name] [filter name] [priority] [inet|inet6]
```

So for me the good filter_options is 
```
filter_options: ['nftables','INPUT','0','inet']
```
But error here is : 
```
The error was: capirca.lib.nftables.HeaderError: Invalid address family in header: nftables. Supported: frozenset({'mixed', 'inet6', 'inet'})
```
